version: "3"

networks:
  gitea:
    external: false

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: ".env"
    volumes:
      - ./storage:/storage
